name: user-study
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - pip
  - pip:
      - absl-py==2.3.1
      - attrs==25.4.0
      - blinker==1.9.0
      - cffi==2.0.0
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - flask==3.1.2
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - itsdangerous==2.2.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mediapipe==0.10.21
      - ml-dtypes==0.5.3
      - numpy==1.26.4
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.9.0.80
      - opt-einsum==3.4.0
      - packaging==25.0
      - pillow==12.0.0
      - protobuf==4.25.8
      - pycparser==2.23
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - six==1.17.0
      - sounddevice==0.5.3
      - werkzeug==3.1.3
